version: "3.9"
services:
  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myPassword
    ports:
      - 5432:5432
  
  web:
    depends_on:
      - postgres
    build: .
    ports:
      - "5000:5000"